% This function calculates the 1st order approximation of the mean of a
% bunch of matrices based on the Taylor expansion of the matrix logarithm
% and the definition of mean of a probability density function.

% Input: X is a 4 by 4*n rigid transformation matrices
% Output: M_T1 is the mean of the 1st order approximation of Taylor
% expansion

% Change of this m file doesn't automatically change the executable generated by 
% mean_Taylor_2nd.m
function [M_1, M_hat] = mean_Taylor_1st( X ) %#codegen

n =  size(X, 2)/4;

M_hat = zeros(4);
M_1 = zeros(4);

for i = 1:n
    M_hat = M_hat + X(:,(i-1)*4+1:i*4);
end

M_hat = 1/n*M_hat;  % Note that M_hat doesn't belong to SE(3)

M_1 = orthog(M_hat);

end